// Где клиент разбирает каждое событие сервера. Ключи — все типы событий из контракта (lib/api.gen.ts): новое
// событие сервера не пройдёт проверку типов, пока здесь не записано, кто его обрабатывает или почему оно не нужно.
import type { Envelope } from "./types";

export const EVENT_HANDLERS = {
  "audio.state": "stores/game.ts, lib/useGameSocket.ts (звук)",
  "auth.ok": "lib/socket.ts (вход в кампанию)",
  "campaign.deleted": "lib/socket.ts (соединение закрывается)",
  "campaign.epilogue": "не нужно: эпилог приходит сообщениями чата",
  "campaign.plan": "lib/useGameSocket.ts (сбой подготовки сюжета)",
  "character.bonds": "не нужно: game/BondsForm.tsx опрашивает связи сам",
  "character.review_failed": "не нужно: pages/CampaignHeroPage.tsx опрашивает героя, пока он на проверке",
  "character.reviewed": "не нужно: pages/CampaignHeroPage.tsx опрашивает героя, пока он на проверке",
  "character.sheet": "stores/game.ts",
  "character.updated": "stores/game.ts",
  "entity.card": "stores/game.ts",
  error: "stores/game.ts, lib/useGameSocket.ts, lib/socket.ts",
  "knowledge.revealed": "stores/game.ts, lib/useGameSocket.ts, game/map.ts",
  "map.changed": "game/map.ts",
  "map.state": "game/map.ts",
  "map.step.result": "game/map.ts",
  "master.status": "stores/game.ts",
  "master.tool.result": "master/tools.ts",
  "message.chunk": "stores/game.ts",
  "message.new": "stores/game.ts",
  "message.notice": "stores/game.ts",
  "message.rejected": "stores/game.ts",
  "message.state": "stores/game.ts",
  "message.withdrawn": "stores/game.ts",
  pong: "не нужно: ответ на ping держит соединение",
  "presence.changed": "stores/game.ts",
  "reaction.closed": "stores/game.ts",
  "reaction.prompt": "stores/game.ts",
  "rest.ended": "stores/game.ts",
  "rest.vote": "stores/game.ts",
  "scene.updated": "stores/game.ts, game/map.ts",
  "seat.changed": "lib/socket.ts (запрос состояния заново)",
  "session.ended": "lib/socket.ts (запрос состояния заново)",
  "session.paused": "lib/socket.ts (запрос состояния заново)",
  "session.started": "lib/socket.ts (запрос состояния заново)",
  "session.summary": "stores/game.ts",
  "stand_in.changed": "stores/game.ts, lib/useGameSocket.ts",
  "stat.explained": "stores/game.ts",
  "state.actions": "stores/game.ts",
  "state.snapshot": "stores/game.ts, lib/socket.ts",
  "turn.changed": "stores/game.ts",
  "vote.ended": "stores/game.ts, lib/useGameSocket.ts",
  "vote.started": "stores/game.ts",
  "vote.updated": "stores/game.ts",
} satisfies Record<Envelope["type"], string>;
