import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { Link } from "react-router-dom";
import { actionOf, STATUS_TEXT, statusOf, when } from "../lib/cards";
import Avatar from "./Avatar";
const ROLE = { player: "игрок", master: "мастер" };
export default function CampaignCardView({ c }) {
    const status = statusOf(c);
    const action = actionOf(c);
    const roles = [c.my_role ? ROLE[c.my_role] : null, c.is_owner ? "владелец" : null].filter(Boolean).join(", ");
    const last = when(c.last_session_at);
    return (_jsxs("article", { className: "card flex flex-col gap-3 p-4", children: [_jsxs("div", { className: "flex items-start justify-between gap-3", children: [_jsxs("div", { className: "min-w-0", children: [_jsx("h3", { className: "truncate text-lg font-semibold", children: c.name }), _jsx("p", { className: "text-muted", children: c.world ?? "Базовые правила" })] }), _jsx("span", { className: `shrink-0 rounded-full px-2 py-0.5 text-xs ${status === "live" ? "bg-accent text-on-accent" : "border border-line text-muted"}`, children: STATUS_TEXT[status] })] }), _jsxs("p", { className: "text-muted", children: [roles && _jsxs(_Fragment, { children: ["\u041C\u043E\u044F \u0440\u043E\u043B\u044C: ", roles, ". "] }), c.hero && (_jsxs(_Fragment, { children: ["\u0413\u0435\u0440\u043E\u0439: ", _jsx("span", { className: "text-ink", children: c.hero.name }), c.hero.level ? `, ${c.hero.level} ур.` : ""] }))] }), _jsx("div", { className: "flex flex-wrap gap-1.5", "aria-label": "\u041E\u0442\u0440\u044F\u0434", children: c.party.map((m) => (_jsx(Avatar, { name: m.hero_name ?? m.user_name, role: m.role, occupant: m.occupant_type, presence: m.occupant_type === "human" ? (m.online ? "online" : "offline") : null }, m.seat_id))) }), c.recap && (_jsxs("p", { className: "font-narration text-sm leading-relaxed", children: [_jsx("span", { className: "text-muted", children: "\u0420\u0430\u043D\u0435\u0435 \u0432 \u043A\u0430\u043C\u043F\u0430\u043D\u0438\u0438\u2026 " }), c.recap] })), _jsxs("div", { className: "mt-auto flex items-center justify-between gap-2", children: [_jsx("span", { className: "text-xs text-muted", children: last ? `Прошлая сессия: ${last}` : "" }), _jsx(Link, { to: action.href, reloadDocument: action.href.startsWith("/legacy"), className: `btn ${action.primary ? "btn-primary" : ""}`, children: action.label })] })] }));
}
